### ISSUE TITLE
Please apply an Open Source license

### ISSUE THREAD

**Issue by danielfernandez** [starschema/business-objects-universe-extractor#15]
Thanks for your very useful library.

I've seen in #10 that you consider this project _"free for commercial use"_ (thanks).

But **would you please consider applying an open source license to it?** My recommendation would be the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0).

This should be easy and can be done from GitHub's interface itself (see [instructions here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)).

Applying a real Open Source license would have many advantages for you, like a clear limitation of StarSchema's liability and ensuring authorship on your code, but it would also provide users a clear base on which to base any modifications or other uses, all of which would be covered and regulated by such license.

**Comment by tfoldi** [comment]
Hey Daniel, just added MIT license. Hope this Works
