### ISSUE TITLE
Error resolving version for plugin 'org.apache.maven.plugins:maven-shade-plugin'

### ISSUE THREAD

**Issue by rvschaffer** [starschema/business-objects-universe-extractor#7]
Executing the BOMetadataExtraction.bat throws the following error:
```
[ERROR] Error resolving version for plugin 'org.apache.maven.plugins:maven-shade-plugin' from the repositories [local (C:\Users\admin\Desktop\business
-objects-universe-extractor-master\m2), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]
```
Forcing the version of the plugin inside the projects pom.xml file to <version>3.2.0</version> makes it go a little further, but brings another error:

```
[ERROR] No plugin found for prefix 'exec' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from
 the repositories [local (C:\Users\admin\Desktop\business-objects-universe-extractor-master\m2), central (https://repo.maven.apache.org/maven2)] -> [H
elp 1]
```

I think this is probably because of the Maven version. I am using the latest available (3.5.4). 
The question is: Which Maven version is known to work?

**Comment by TheDago** [comment]
Hello!

We are using Maven version 3.5.4 (same one as you), but we could not reproduce the error. This problem usually connects to some proxy problem. If you are behind a firewall please check your proxy settings. You can read more about maven and proxies [here](https://maven.apache.org/settings.html#Proxies) and [here](https://maven.apache.org/guides/mini/guide-proxies.html). 
If this does not help, try adding the maven repository explicitly to the pom.xml:
``` 
<pluginRepositories>
      <pluginRepository>
          <id>maven2</id>
          <url>https://repo.maven.apache.org/maven2/</url>
      </pluginRepository>
 </pluginRepositories>
```
If nothing above works, please send the whole output of the _BOMetadataExtraction.bat_ run and other information about your environment e.g.: OS, Java version.

**Comment by rvschaffer** [comment]
We found the problem! It's certificate related. Removing certificate
verification solved.
Thank you for your help!
Regards,
Rafael

**Comment by PrajaktaBirnale** [comment]
Can you please provide the details regarding which certificate we need to remove

**Comment by mastudily** [comment]
This works for me

'<pluginRepositories>
      <pluginRepository>
          <id>maven2</id>
          <url>https://repo.maven.apache.org/maven2/</url>
      </pluginRepository>
 </pluginRepositories>'

Thanks https://github.com/TheDago

**Comment by mastudily** [comment]
`<pluginRepositories>
      <pluginRepository>
          <id>maven2</id>
          <url>https://repo.maven.apache.org/maven2/</url>
      </pluginRepository>
 </pluginRepositories>
`

**Comment by tariqghd** [comment]
Hello 
may you specify where I can change this value which file and path please.

I get the error before the project created I don't have POM.xml file I'm getting the error during project creation. I need to know where the project creation maven dependency file located in netbeans  
 
Thanks
Tariq
